version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    networks:
      - mynetwork
    volumes:
      - ./src:/app/src

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  postgres_logs: