version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - .env
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
