version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - .env
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
